spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.model=${SPRING_AI_GOOGLE_GENAI_CHAT_MODEL}
spring.ai.google.genai.embedding.text.model=${SPRING_AI_GOOGLE_GENAI_EMBEDDING_TEXT_MODEL}
spring.ai.google.genai.embedding.api-key=${SPRING_AI_GOOGLE_GENAI_EMBEDDING_API_KEY}
spring.ai.vectorstore.qdrant.host=${SPRING_AI_VECTORSTORE_QDRANT_HOST}
spring.ai.vectorstore.qdrant.collection-name=${SPRING_AI_VECTORSTORE_QDRANT_COLLECTION_NAME}
spring.ai.vectorstore.qdrant.port=${SPRING_AI_VECTORSTORE_QDRANT_PORT}
spring.ai.vectorstore.qdrant.initialize-schema=${SPRING_AI_VECTORSTORE_QDRANT_INITIALIZE_SCHEMA}
spring.ai.model.embedding=${SPRING_AI_MODEL_EMBEDDING}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}