spring.application.name=fileVerification
server.port = 8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${rabbitmq-username}
spring.rabbitmq.password=${rabbitmq-password}

aws.s3.bucket-name=ai-helpdesk-tanuj
aws.region=ap-south-1
aws.access-key=${aws-access-key}
aws.secret-key=${aws-secret-key}

spring.ai.google.genai.api-key= ${gemini-api-key}
spring.ai.google.genai.chat.options.model= ${gemini-model}