spring.application.name=${SPRING_APPLICATION_NAME}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.model=${SPRING_AI_GOOGLE_GENAI_CHAT_MODEL}
spring.ai.google.genai.embedding.text.model=${SPRING_AI_GOOGLE_GENAI_EMBEDDING_TEXT_MODEL}
spring.ai.google.genai.embedding.api-key=${SPRING_AI_GOOGLE_GENAI_EMBEDDING_API_KEY}
spring.ai.vectorstore.qdrant.host=${SPRING_AI_VECTORSTORE_QDRANT_HOST}
spring.ai.vectorstore.qdrant.collection-name=${SPRING_AI_VECTORSTORE_QDRANT_COLLECTION_NAME}
spring.ai.vectorstore.qdrant.port=${SPRING_AI_VECTORSTORE_QDRANT_PORT}
spring.ai.vectorstore.qdrant.initialize-schema=${SPRING_AI_VECTORSTORE_QDRANT_INITIALIZE_SCHEMA}
spring.ai.model.embedding=${SPRING_AI_MODEL_EMBEDDING}

springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.invitation-expiration=${JWT_INVITATION_EXPIRATION}

aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.region=${AWS_REGION}

spring.servlet.multipart.enabled=${SPRING_SERVLET_MULTIPART_ENABLED}
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

spring.ai.chat.memory.repository.jdbc.initialize-schema=${SPRING_AI_CHAT_MEMORY_REPOSITORY_JDBC_INITIALIZE_SCHEMA}